name: main

on: [push, pull_request]

jobs:
  package:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Publish
        run: dotnet publish YoutubeDownloader/ -o YoutubeDownloaderZ/bin/Publish --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YoutubeDownloader
          path: YoutubeDownloaderZ/bin/Publish

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: YoutubeDownloader
          path: YoutubeDownloaderZ

      - name: Create package
        run: Compress-Archive -Path YoutubeDownloaderZ/* -DestinationPath YoutubeDownloaderZ.zip -Force
        shell: pwsh

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: YoutubeDownloader
          path: YoutubeDownloaderZPreview

      - name: Create package preview
        run: Compress-Archive -Path YoutubeDownloaderZPreview/* -DestinationPath YoutubeDownloaderZPreview.zip -Force
        shell: pwsh        

      - name: Get release version
        id: get_version
        uses: dawidd6/action-get-tag@v1

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            YoutubeDownloaderZ.zip
            YoutubeDownloaderZPreview.zip
          body: |
            [Changelog](https://github.com/RauCu/YoutubeDownloaderZ/blob/${{ steps.get_version.outputs.tag }}/Changelog.md)
